---
blank_issues_enabled: false
contact_links:
  - name: Create-Starknet-App Community Support
    url: https://github.com/satyambnsal/starknet-dapp/discussions
    about: Please ask and answer questions here.
